Revert a change to type analysis that broke builds
This just reverts a change that was making things work in the past. The error when building on Unity 2018.3.8f1 was:

TypeLoadException: Could not resolve type with token 01000052 (from typeref, class/assembly System.Security.SecuritySafeCriticalAttribute, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
  at (wrapper managed-to-native) System.MonoCustomAttrs.GetCustomAttributesInternal(System.Reflection.ICustomAttributeProvider,System.Type,bool)
  at System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inheritedOnly) [0x00013] in <91744f54f98f4b5d840497556a31caa1>:0 
  at System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) [0x00037] in <91744f54f98f4b5d840497556a31caa1>:0 
  at System.Reflection.MonoMethod.GetCustomAttributes (System.Type attributeType, System.Boolean inherit) [0x00000] in <91744f54f98f4b5d840497556a31caa1>:0 
  at Zenject.Internal.ReflectionTypeAnalyzer+<>c__DisplayClass7_1.<GetMethodInfos>b__1 (System.Type a) [0x00000] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Util\ZenReflectionTypeAnalyzer.cs:77 
  at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0002c] in <1d99ff3466ae4dc2aaaaa10b31d9f99b>:0 
  at Zenject.Internal.ReflectionTypeAnalyzer+<>c.<GetMethodInfos>b__7_0 (System.Reflection.MethodInfo x) [0x0000d] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Util\ZenReflectionTypeAnalyzer.cs:77 
  at System.Linq.Enumerable+WhereArrayIterator`1[TSource].ToList () [0x00019] in <1d99ff3466ae4dc2aaaaa10b31d9f99b>:0 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <1d99ff3466ae4dc2aaaaa10b31d9f99b>:0 
  at Zenject.Internal.ReflectionTypeAnalyzer.GetMethodInfos (System.Type type) [0x00014] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Util\ZenReflectionTypeAnalyzer.cs:76 
  at Zenject.Internal.ReflectionTypeAnalyzer.GetReflectionInfo (System.Type type) [0x0004a] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Util\ZenReflectionTypeAnalyzer.cs:46 
  at Zenject.TypeAnalyzer.CreateTypeInfoFromReflection (System.Type type) [0x0000e] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Util\TypeAnalyzer.cs:232 
  at Zenject.TypeAnalyzer.GetInfoInternal (System.Type type) [0x00086] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Util\TypeAnalyzer.cs:213 
  at Zenject.TypeAnalyzer.TryGetInfo (System.Type type) [0x0001a] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Util\TypeAnalyzer.cs:131 
  at Zenject.TypeAnalyzer.TryGetInfo (System.Type type) [0x0006a] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Util\TypeAnalyzer.cs:143 
  at Zenject.TypeAnalyzer.TryGetInfo (System.Type type) [0x0006a] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Util\TypeAnalyzer.cs:143 
  at Zenject.TypeAnalyzer.TryGetInfo (System.Type type) [0x0006a] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Util\TypeAnalyzer.cs:143 
  at Zenject.TypeAnalyzer.TryGetInfo (System.Type type) [0x0006a] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Util\TypeAnalyzer.cs:143 
  at Zenject.TypeAnalyzer.HasInfo (System.Type type) [0x00001] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Util\TypeAnalyzer.cs:93 
  at Zenject.Internal.ZenUtilInternal.IsInjectableMonoBehaviourType (System.Type type) [0x00001] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Util\ZenUtilInternal.cs:211 
  at Zenject.Internal.ZenUtilInternal.GetInjectableMonoBehavioursUnderGameObjectInternal (UnityEngine.GameObject gameObject, System.Collections.Generic.List`1[T] injectableComponents) [0x000b9] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Util\ZenUtilInternal.cs:200 
  at Zenject.Internal.ZenUtilInternal.GetInjectableMonoBehavioursUnderGameObject (UnityEngine.GameObject gameObject, System.Collections.Generic.List`1[T] injectableComponents) [0x00002] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Util\ZenUtilInternal.cs:153 
  at Zenject.ProjectContext.GetInjectableMonoBehaviours (System.Collections.Generic.List`1[T] monoBehaviours) [0x0000d] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Install\Contexts\ProjectContext.cs:266 
  at Zenject.ProjectContext.Initialize () [0x0007c] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Install\Contexts\ProjectContext.cs:227 
  at Zenject.ProjectContext.InstantiateAndInitialize () [0x00097] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Install\Contexts\ProjectContext.cs:162 
  at Zenject.ProjectContext.get_Instance () [0x00011] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Install\Contexts\ProjectContext.cs:59 
  at Zenject.SceneContext.RunInternal () [0x00001] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Install\Contexts\SceneContext.cs:128 
  at Zenject.RunnableContext.Run () [0x00015] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Install\Contexts\RunnableContext.cs:36 
  at Zenject.RunnableContext.Initialize () [0x00016] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Install\Contexts\RunnableContext.cs:22 
  at Zenject.SceneContext.Awake () [0x00002] in D:\Source Tree\Repos\Match\Assets\Plugins\Zenject\Source\Install\Contexts\SceneContext.cs:113